// reactjs/master/jsx/components/Elements/Buttons.jsx
import React from 'react';
import ContentWrapper from '../Layout/ContentWrapper';
import { Grid, Row, Col, Panel, Button, ButtonGroup, ButtonToolbar, SplitButton, DropdownButton, MenuItem, Pagination, Pager } from 'react-bootstrap';

class Buttons extends React.Component {

    constructor(props, context) {
        super(props, context);
        this.state = {
            activePage: 1
        };
    }

    handleSelect(event, selectedEvent) {
        this.setState({
            activePage: selectedEvent.eventKey
        });
    }

    renderDropdownButton(title, i) {
        return (
            <DropdownButton bsStyle={ title.toLowerCase() } title={ title } key={ i } id={ `dropdown-basic-${i}` }>
                <MenuItem eventKey="1">Action</MenuItem>
                <MenuItem eventKey="2">
                    Another action
                </MenuItem>
                <MenuItem eventKey="3" active>
                    Active Item
                </MenuItem>
                <MenuItem divider />
                <MenuItem eventKey="4">
                    Separated link
                </MenuItem>
            </DropdownButton>
            );
    }

    renderDropdownSplitButton(title, i) {
        return (
            <SplitButton bsStyle={ title.toLowerCase() } title={ title } key={ i } id={ `split-button-basic-${i}` }>
                <MenuItem eventKey="1">Action</MenuItem>
                <MenuItem eventKey="2">
                    Another action
                </MenuItem>
                <MenuItem eventKey="3">
                    Something else here
                </MenuItem>
                <MenuItem divider />
                <MenuItem eventKey="4">
                    Separated link
                </MenuItem>
            </SplitButton>
            );
    }

    render() {
        // Used to render DropdownButton examples
        const BUTTONS = ['Default', 'Primary', 'Success', 'Info', 'Warning', 'Danger']
        return (
            <ContentWrapper>
                <h3>Buttons</h3>
                { /* START row */ }
                <Row>
                    <Col md={ 12 }>
                        { /* START panel */ }
                        <Panel header="Buttons">
                            <ButtonToolbar>
                                { /* Standard button */ }
                                <Button>Default</Button>
                                { /* Provides extra visual weight and identifies the primary action in a set of buttons */ }
                                <Button bsStyle="primary">Primary</Button>
                                { /* Indicates a successful or positive action */ }
                                <Button bsStyle="success">Success</Button>
                                { /* Contextual button for informational alert messages */ }
                                <Button bsStyle="info">Info</Button>
                                { /* Indicates caution should be taken with this action */ }
                                <Button bsStyle="warning">Warning</Button>
                                { /* Indicates a dangerous or potentially negative action */ }
                                <Button bsStyle="danger">Danger</Button>
                                <Button bsClass="btn btn-inverse" className="mb-sm">Inverse</Button>
                                <Button bsClass="btn btn-green" className="mb-sm">Green</Button>
                                <Button bsClass="btn btn-purple" className="mb-sm">Purple</Button>
                                <Button bsClass="btn btn-pink" className="mb-sm">Pink</Button>
                                { /* Deemphasize a button by making it look like a link while maintaining button behavior */ }
                                <Button bsStyle="link">Link</Button>
                            </ButtonToolbar>
                        </Panel>
                        { /* END panel */ }
                    </Col>
                </Row>
                { /* END row */ }
                { /* START panel */ }
                <Panel header="Button Labeled">
                    { /* Success button with label  */ }
                    <Button bsClass="btn btn-labeled btn-success mr">
                        <span className="btn-label"><i className="fa fa-check"></i></span> Success
                    </Button>
                    { /* Danger button with label  */ }
                    <Button bsClass="btn btn-labeled btn-danger mr">
                        <span className="btn-label"><i className="fa fa-times"></i></span> Danger
                    </Button>
                    { /* Info button with label  */ }
                    <Button bsClass="btn btn-labeled btn-info mr">
                        <span className="btn-label"><i className="fa fa-exclamation"></i></span> Info
                    </Button>
                    { /* Warning button with label  */ }
                    <Button bsClass="btn btn-labeled btn-warning mr">
                        <span className="btn-label"><i className="fa fa-warning"></i></span> Warning
                    </Button>
                    { /* Standard button with label  */ }
                    <Button bsClass="btn btn-labeled btn-default mr">
                        <span className="btn-label"><i className="fa fa-arrow-left"></i></span> Left
                    </Button>
                    { /* Standard button with label on the right side  */ }
                    <Button bsClass="btn btn-labeled btn-default">
                        Right
                        <span className="btn-label btn-label-right"><i className="fa fa-arrow-right"></i></span>
                    </Button>
                </Panel>
                { /* END panel */ }
                { /* START row */ }
                <Row>
                    <Col md={ 6 }>
                        { /* START panel */ }
                        <Panel header="Button sizing">
                            <Row>
                                <Col lg={ 6 }>
                                    <p>
                                        <Button bsStyle="primary" bsSize="large">
                                            Large button
                                        </Button>
                                        <Button bsStyle="default" bsSize="large">
                                            Large button
                                        </Button>
                                    </p>
                                    <p>
                                        <Button bsStyle="primary">
                                            Default button
                                        </Button>
                                        <Button bsStyle="default">
                                            Default button
                                        </Button>
                                    </p>
                                </Col>
                                <Col lg={ 6 }>
                                    <p>
                                        <Button bsStyle="primary" bsSize="small">
                                            Small button
                                        </Button>
                                        <Button bsStyle="default" bsSize="small">
                                            Small button
                                        </Button>
                                    </p>
                                    <p>
                                        <Button bsStyle="primary" bsSize="xsmall">
                                            Extra small button
                                        </Button>
                                        <Button bsStyle="default" bsSize="xsmall">
                                            Extra small button
                                        </Button>
                                    </p>
                                </Col>
                            </Row>
                        </Panel>
                        { /* END panel */ }
                    </Col>
                    <Col md={ 6 }>
                        { /* START panel */ }
                        <Panel header="Button group">
                            <p>
                            </p>
                            <ButtonGroup>
                                <Button>Left</Button>
                                <Button>Middle</Button>
                                <Button>Right</Button>
                            </ButtonGroup>
                            <p>
                            </p>
                            <p>
                            </p>
                            <ButtonGroup>
                                <Button>1</Button>
                                <Button>2</Button>
                                <Button>3</Button>
                                <Button>4</Button>
                            </ButtonGroup>
                            <ButtonGroup>
                                <Button>5</Button>
                                <Button>6</Button>
                                <Button>7</Button>
                            </ButtonGroup>
                            <ButtonGroup>
                                <Button>8</Button>
                            </ButtonGroup>
                        </Panel>
                        { /* END panel */ }
                    </Col>
                </Row>
                { /* END row */ }
                {/* START panel */}
                <Panel header="Outline Buttons">
                    <button type="button" className="mb-sm mr-sm btn btn-default btn-outline">Default</button>
                    <button type="button" className="mb-sm mr-sm btn btn-primary btn-outline">Primary</button>
                    <button type="button" className="mb-sm mr-sm btn btn-success btn-outline">Success</button>
                    <button type="button" className="mb-sm mr-sm btn btn-info btn-outline">Info</button>
                    <button type="button" className="mb-sm mr-sm btn btn-warning btn-outline">Warning</button>
                    <button type="button" className="mb-sm mr-sm btn btn-danger btn-outline">Danger</button>
                    <button type="button" className="mb-sm mr-sm btn btn-inverse btn-outline">Inverse</button>
                    <button type="button" className="mb-sm mr-sm btn btn-green btn-outline">Green</button>
                    <button type="button" className="mb-sm mr-sm btn btn-purple btn-outline">Purple</button>
                    <button type="button" className="mb-sm mr-sm btn btn-pink btn-outline">Pink</button>
                    <br />
                    <br />
                    <button type="button" className="mb-sm mr-sm btn-lg btn btn-primary btn-outline">Outline Large</button>
                    <button type="button" className="mb-sm mr-sm btn-sm btn btn-primary btn-outline">Outline Small</button>
                    <button type="button" className="mb-sm mr-sm btn-xs btn btn-primary btn-outline">Outline xSmall</button>
                </Panel>
                {/* END panel */}
                { /* START row */ }
                <Row>
                    <Col md={ 6 }>
                        { /* START panel */ }
                        <Panel header="Button Pills">
                            <p>
                                Pill left
                            </p>
                            <p>
                                <Button bsClass="btn btn-pill-left btn-default">Default</Button>
                                <Button bsClass="btn btn-pill-left btn-primary">Primary</Button>
                                <Button bsClass="btn btn-pill-left btn-success">Success</Button>
                                <Button bsClass="btn btn-pill-left btn-info">Info</Button>
                                <Button bsClass="btn btn-pill-left btn-warning">Warning</Button>
                                <Button bsClass="btn btn-pill-left btn-danger">Danger</Button>
                                <Button bsClass="btn btn-pill-left btn-inverse">Inverse</Button>
                            </p>
                            <p>
                                Pill right
                            </p>
                            <p>
                                <Button bsClass="btn btn-pill-right btn-default">Default</Button>
                                <Button bsClass="btn btn-pill-right btn-primary">Primary</Button>
                                <Button bsClass="btn btn-pill-right btn-success">Success</Button>
                                <Button bsClass="btn btn-pill-right btn-info">Info</Button>
                                <Button bsClass="btn btn-pill-right btn-warning">Warning</Button>
                                <Button bsClass="btn btn-pill-right btn-danger">Danger</Button>
                                <Button bsClass="btn btn-pill-right btn-inverse">Inverse</Button>
                            </p>
                        </Panel>
                        { /* END panel */ }
                    </Col>
                    <Col md={ 6 }>
                        { /* START panel */ }
                        <Panel header="Button Oval">
                            <Button bsClass="btn btn-oval btn-default">Default</Button>
                            <Button bsClass="btn btn-oval btn-primary">Primary</Button>
                            <Button bsClass="btn btn-oval btn-success">Success</Button>
                            <Button bsClass="btn btn-oval btn-info">Info</Button>
                            <Button bsClass="btn btn-oval btn-warning">Warning</Button>
                            <Button bsClass="btn btn-oval btn-danger">Danger</Button>
                            <Button bsClass="btn btn-oval btn-inverse">Inverse</Button>
                        </Panel>
                        { /* END panel */ }
                        { /* START panel */ }
                        <Panel header="Button Square">
                            <Button bsClass="btn btn-square btn-default">Default</Button>
                            <Button bsClass="btn btn-square btn-primary">Primary</Button>
                            <Button bsClass="btn btn-square btn-success">Success</Button>
                            <Button bsClass="btn btn-square btn-info">Info</Button>
                            <Button bsClass="btn btn-square btn-warning">Warning</Button>
                            <Button bsClass="btn btn-square btn-danger">Danger</Button>
                            <Button bsClass="btn btn-square btn-inverse">Inverse</Button>
                        </Panel>
                        { /* END panel */ }
                    </Col>
                </Row>
                { /* END row */ }
                { /* START row */ }
                <Row>
                    <Col md={ 6 }>
                        { /* START panel */ }
                        <Panel header="Button dropdown">
                            <ButtonToolbar>
                                { BUTTONS.map(this.renderDropdownButton) }
                            </ButtonToolbar>
                        </Panel>
                        { /* END panel */ }
                    </Col>
                    <Col md={ 6 }>
                        { /* START panel */ }
                        <Panel header="Split button dropdown">
                            <ButtonToolbar>
                                { BUTTONS.map(this.renderDropdownSplitButton) }
                            </ButtonToolbar>
                        </Panel>
                        { /* END panel */ }
                    </Col>
                </Row>
                { /* END row */ }
                { /* START panel */ }
                <Panel header="Pagination">
                    { /* START row */ }
                    <Row>
                        <Col lg={ 6 }>
                            <div>
                                <h4>Sizes</h4>
                                <Pagination bsSize="large" items={ 10 } activePage={ this.state.activePage } onSelect={ this.handleSelect.bind(this) } />
                                <br />
                                <Pagination bsSize="medium" items={ 10 } activePage={ this.state.activePage } onSelect={ this.handleSelect.bind(this) } />
                                <br />
                                <Pagination bsSize="small" items={ 10 } activePage={ this.state.activePage } onSelect={ this.handleSelect.bind(this) } />
                            </div>
                        </Col>
                        <Col lg={ 6 }>
                            <h4>Pager</h4>
                            <Pager>
                                <Pager.Item href="#">Previous</Pager.Item>
                                { ' ' }
                                <Pager.Item href="#">Next</Pager.Item>
                            </Pager>
                            <Pager>
                                <Pager.Item previous href="#">
                                    &larr; Previous Page
                                </Pager.Item>
                                <Pager.Item next href="#">
                                    Next Page &rarr;
                                </Pager.Item>
                            </Pager>
                        </Col>
                    </Row>
                    { /* END row */ }
                </Panel>
                { /* END panel */ }
            </ContentWrapper>
            );
    }
}

export default Buttons;

// angular2/ng2angle/src/app/routes/elements/buttons/buttons.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-buttons',
    templateUrl: './buttons.component.html',
    styleUrls: ['./buttons.component.scss']
})
export class ButtonsComponent implements OnInit {
    // buttons
    public singleModel: boolean = true;
    public radioModel: string = 'Middle';
    public checkModel: any = { left: false, middle: true, right: false };

    // pagination/pager
    public totalItems: number = 64;
    public currentPage: number = 4;

    public maxSize: number = 5;
    public bigTotalItems: number = 175;
    public bigCurrentPage: number = 1;

    public setPage(pageNo: number): void {
        this.currentPage = pageNo;
    };

    public pageChanged(event: any): void {
        console.log('Page changed to: ' + event.page);
        console.log('Number items per page: ' + event.itemsPerPage);
    };

    constructor() { }

    ngOnInit() {
    }

}

<div class="content-heading">Buttons</div>
<!-- START row-->
<div class="row">
    <div class="col-md-6">
        <!-- START panel-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Button colors</h3>
            </div>
            <div class="panel-body">
                <button class="mb-sm btn btn-default" type="button">Default</button>
                <button class="mb-sm btn btn-primary" type="button">Primary</button>
                <button class="mb-sm btn btn-success" type="button">Success</button>
                <button class="mb-sm btn btn-info" type="button">Info</button>
                <button class="mb-sm btn btn-warning" type="button">Warning</button>
                <button class="mb-sm btn btn-danger" type="button">Danger</button>
                <button class="mb-sm btn btn-inverse" type="button">Inverse</button>
                <button class="mb-sm btn btn-green" type="button">Green</button>
                <button class="mb-sm btn btn-purple" type="button">Purple</button>
                <button class="mb-sm btn btn-pink" type="button">Pink</button>
                <br/>
                <br/><a class="btn btn-link" href="#">Button Link</a>
                <button class="btn btn-default" type="button">
                    <strong>button tag</strong>
                </button>
                <a class="btn btn-default" href="#">
                    <strong>anchor tag</strong>
                </a>
            </div>
        </div>
        <!-- END panel-->
    </div>
    <div class="col-md-6">
        <!-- START panel-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Button Labeled</h3>
            </div>
            <div class="panel-body">
                <!-- Success button with label-->
                <button class="btn btn-labeled btn-success" type="button">
                    <span class="btn-label"><i class="fa fa-check"></i>
               </span>Success</button>
                <!-- Danger button with label-->
                <button class="btn btn-labeled btn-danger" type="button">
                    <span class="btn-label"><i class="fa fa-times"></i>
               </span>Danger</button>
                <!-- Info button with label-->
                <button class="btn btn-labeled btn-info" type="button">
                    <span class="btn-label"><i class="fa fa-exclamation"></i>
               </span>Info</button>
                <!-- Warning button with label-->
                <button class="btn btn-labeled btn-warning" type="button">
                    <span class="btn-label"><i class="fa fa-warning"></i>
               </span>Warning</button>
                <br/>
                <br/>
                <!-- Standard button with label-->
                <button class="btn btn-labeled btn-default" type="button">
                    <span class="btn-label"><i class="fa fa-arrow-left"></i>
               </span>Left</button>
                <!-- Standard button with label on the right side-->
                <button class="btn btn-labeled btn-default" type="button">Right
                    <span class="btn-label btn-label-right"><i class="fa fa-arrow-right"></i>
               </span>
                </button>
            </div>
        </div>
        <!-- END panel-->
    </div>
</div>
<!-- END row-->
<!-- START row-->
<div class="row">
    <div class="col-md-6">
        <!-- START panel-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Button sizing</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6">
                        <p>
                            <button class="btn btn-primary btn-lg" type="button">Large button</button>
                            <button class="btn btn-default btn-lg" type="button">Large button</button>
                        </p>
                        <p>
                            <button class="btn btn-primary" type="button">Default button</button>
                            <button class="btn btn-default" type="button">Default button</button>
                        </p>
                    </div>
                    <div class="col-lg-6">
                        <p>
                            <button class="btn btn-primary btn-sm" type="button">Small button</button>
                            <button class="btn btn-default btn-sm" type="button">Small button</button>
                        </p>
                        <p>
                            <button class="btn btn-primary btn-xs" type="button">Extra small button</button>
                            <button class="btn btn-default btn-xs" type="button">Extra small button</button>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <!-- END panel-->
    </div>
    <div class="col-md-6">
        <!-- START panel-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Button group</h3>
            </div>
            <div class="panel-body">
                <p></p>
                <div class="btn-group">
                    <button class="btn btn-default" type="button">Left</button>
                    <button class="btn btn-default" type="button">Middle</button>
                    <button class="btn btn-default" type="button">Right</button>
                </div>
                <p></p>
                <p></p>
                <div class="btn-group">
                    <button class="btn btn-default" type="button">1</button>
                    <button class="btn btn-default" type="button">2</button>
                    <button class="btn btn-default" type="button">3</button>
                    <button class="btn btn-default" type="button">4</button>
                </div>
                <div class="btn-group">
                    <button class="btn btn-default" type="button">5</button>
                    <button class="btn btn-default" type="button">6</button>
                    <button class="btn btn-default" type="button">7</button>
                </div>
                <div class="btn-group">
                    <button class="btn btn-default" type="button">8</button>
                </div>
            </div>
        </div>
        <!-- END panel-->
    </div>
</div>
<!-- END row-->
<!-- START panel-->
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Outline Buttons</h3>
    </div>
    <div class="panel-body">
        <button class="mb-sm btn btn-default btn-outline" type="button">Default</button>
        <button class="mb-sm btn btn-primary btn-outline" type="button">Primary</button>
        <button class="mb-sm btn btn-success btn-outline" type="button">Success</button>
        <button class="mb-sm btn btn-info btn-outline" type="button">Info</button>
        <button class="mb-sm btn btn-warning btn-outline" type="button">Warning</button>
        <button class="mb-sm btn btn-danger btn-outline" type="button">Danger</button>
        <button class="mb-sm btn btn-inverse btn-outline" type="button">Inverse</button>
        <button class="mb-sm btn btn-green btn-outline" type="button">Green</button>
        <button class="mb-sm btn btn-purple btn-outline" type="button">Purple</button>
        <button class="mb-sm btn btn-pink btn-outline" type="button">Pink</button>
        <br/>
        <br/>
        <button class="mb-sm btn-lg btn btn-primary btn-outline" type="button">Outline Large</button>
        <button class="mb-sm btn-sm btn btn-primary btn-outline" type="button">Outline Small</button>
        <button class="mb-sm btn-xs btn btn-primary btn-outline" type="button">Outline xSmall</button>
    </div>
</div>
<!-- END panel-->
<!-- START row-->
<div class="row">
    <div class="col-md-6">
        <!-- START panel-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Button Pills</h3>
            </div>
            <div class="panel-body">
                <p>Pill left</p>
                <p>
                    <button class="btn btn-pill-left btn-default" type="button">Default</button>
                    <button class="btn btn-pill-left btn-primary" type="button">Primary</button>
                    <button class="btn btn-pill-left btn-success" type="button">Success</button>
                    <button class="btn btn-pill-left btn-info" type="button">Info</button>
                    <button class="btn btn-pill-left btn-warning" type="button">Warning</button>
                    <button class="btn btn-pill-left btn-danger" type="button">Danger</button>
                    <button class="btn btn-pill-left btn-inverse" type="button">Inverse</button>
                </p>
                <p>Pill right</p>
                <p>
                    <button class="btn btn-pill-right btn-default" type="button">Default</button>
                    <button class="btn btn-pill-right btn-primary" type="button">Primary</button>
                    <button class="btn btn-pill-right btn-success" type="button">Success</button>
                    <button class="btn btn-pill-right btn-info" type="button">Info</button>
                    <button class="btn btn-pill-right btn-warning" type="button">Warning</button>
                    <button class="btn btn-pill-right btn-danger" type="button">Danger</button>
                    <button class="btn btn-pill-right btn-inverse" type="button">Inverse</button>
                </p>
            </div>
        </div>
        <!-- END panel-->
    </div>
    <div class="col-md-6">
        <!-- START panel-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Button Oval</h3>
            </div>
            <div class="panel-body">
                <button class="btn btn-oval btn-default" type="button">Default</button>
                <button class="btn btn-oval btn-primary" type="button">Primary</button>
                <button class="btn btn-oval btn-success" type="button">Success</button>
                <button class="btn btn-oval btn-info" type="button">Info</button>
                <button class="btn btn-oval btn-warning" type="button">Warning</button>
                <button class="btn btn-oval btn-danger" type="button">Danger</button>
                <button class="btn btn-oval btn-inverse" type="button">Inverse</button>
            </div>
        </div>
        <!-- END panel-->
        <!-- START panel-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Button Square</h3>
            </div>
            <div class="panel-body">
                <button class="btn btn-square btn-default" type="button">Default</button>
                <button class="btn btn-square btn-primary" type="button">Primary</button>
                <button class="btn btn-square btn-success" type="button">Success</button>
                <button class="btn btn-square btn-info" type="button">Info</button>
                <button class="btn btn-square btn-warning" type="button">Warning</button>
                <button class="btn btn-square btn-danger" type="button">Danger</button>
                <button class="btn btn-square btn-inverse" type="button">Inverse</button>
            </div>
        </div>
        <!-- END panel-->
    </div>
</div>
<!-- END row-->
<!-- START row-->
<div class="row">
    <div class="col-md-6">
        <!-- START panel-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Button dropdown</h3>
            </div>
            <div class="panel-body">
                <!-- START button group-->
                <div class="btn-group mb-sm" dropdown>
                    <button class="btn dropdown-toggle btn-default" type="button" dropdownToggle>default
                        <span class="caret"></span>
                    </button>
                    <ul dropdownMenu class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a>
                        </li>
                        <li><a href="#">Another action</a>
                        </li>
                        <li><a href="#">Something else here</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a>
                        </li>
                    </ul>
                </div>
                <!-- END button group-->
                <!-- START button group-->
                <div class="btn-group mb-sm" dropdown>
                    <button class="btn dropdown-toggle btn-primary" type="button" dropdownToggle>primary
                        <span class="caret"></span>
                    </button>
                    <ul dropdownMenu class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a>
                        </li>
                        <li><a href="#">Another action</a>
                        </li>
                        <li><a href="#">Something else here</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a>
                        </li>
                    </ul>
                </div>
                <!-- END button group-->
                <!-- START button group-->
                <div class="btn-group mb-sm" dropdown>
                    <button class="btn dropdown-toggle btn-success" type="button" dropdownToggle>success
                        <span class="caret"></span>
                    </button>
                    <ul dropdownMenu class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a>
                        </li>
                        <li><a href="#">Another action</a>
                        </li>
                        <li><a href="#">Something else here</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a>
                        </li>
                    </ul>
                </div>
                <!-- END button group-->
                <!-- START button group-->
                <div class="btn-group mb-sm" dropdown>
                    <button class="btn dropdown-toggle btn-info" type="button" dropdownToggle>info
                        <span class="caret"></span>
                    </button>
                    <ul dropdownMenu class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a>
                        </li>
                        <li><a href="#">Another action</a>
                        </li>
                        <li><a href="#">Something else here</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a>
                        </li>
                    </ul>
                </div>
                <!-- END button group-->
                <!-- START button group-->
                <div class="btn-group mb-sm" dropdown>
                    <button class="btn dropdown-toggle btn-warning" type="button" dropdownToggle>warning
                        <span class="caret"></span>
                    </button>
                    <ul dropdownMenu class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a>
                        </li>
                        <li><a href="#">Another action</a>
                        </li>
                        <li><a href="#">Something else here</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a>
                        </li>
                    </ul>
                </div>
                <!-- END button group-->
                <!-- START button group-->
                <div class="btn-group mb-sm" dropdown>
                    <button class="btn dropdown-toggle btn-danger" type="button" dropdownToggle>danger
                        <span class="caret"></span>
                    </button>
                    <ul dropdownMenu class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a>
                        </li>
                        <li><a href="#">Another action</a>
                        </li>
                        <li><a href="#">Something else here</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a>
                        </li>
                    </ul>
                </div>
                <!-- END button group-->
                <!-- START button group-->
                <div class="btn-group mb-sm" dropdown>
                    <button class="btn dropdown-toggle btn-inverse" type="button" dropdownToggle>inverse
                        <span class="caret"></span>
                    </button>
                    <ul dropdownMenu class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a>
                        </li>
                        <li><a href="#">Another action</a>
                        </li>
                        <li><a href="#">Something else here</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a>
                        </li>
                    </ul>
                </div>
                <!-- END button group-->
            </div>
        </div>
        <!-- END panel-->
    </div>
    <div class="col-md-6">
        <!-- START panel-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title ellipsis">Split button dropdown</h3>
            </div>
            <div class="panel-body">
                <!-- START button group-->
                <div class="btn-group" dropdown>
                    <button class="btn btn-default" type="button">Action</button>
                    <button class="btn dropdown-toggle btn-default" type="button" dropdownToggle>
                        <span class="caret"></span>
                        <span class="sr-only">default</span>
                    </button>
                    <ul dropdownMenu class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a>
                        </li>
                        <li><a href="#">Another action</a>
                        </li>
                        <li><a href="#">Something else here</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a>
                        </li>
                    </ul>
                </div>
                <!-- END button group-->
                <!-- START button group-->
                <div class="btn-group" dropdown>
                    <button class="btn btn-primary" type="button">Action</button>
                    <button class="btn dropdown-toggle btn-primary" type="button" dropdownToggle>
                        <span class="caret"></span>
                        <span class="sr-only">primary</span>
                    </button>
                    <ul dropdownMenu class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a>
                        </li>
                        <li><a href="#">Another action</a>
                        </li>
                        <li><a href="#">Something else here</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a>
                        </li>
                    </ul>
                </div>
                <!-- END button group-->
                <!-- START button group-->
                <div class="btn-group" dropdown>
                    <button class="btn btn-success" type="button">Action</button>
                    <button class="btn dropdown-toggle btn-success" type="button" dropdownToggle>
                        <span class="caret"></span>
                        <span class="sr-only">success</span>
                    </button>
                    <ul dropdownMenu class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a>
                        </li>
                        <li><a href="#">Another action</a>
                        </li>
                        <li><a href="#">Something else here</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a>
                        </li>
                    </ul>
                </div>
                <!-- END button group-->
                <!-- START button group-->
                <div class="btn-group" dropdown>
                    <button class="btn btn-info" type="button">Action</button>
                    <button class="btn dropdown-toggle btn-info" type="button" dropdownToggle>
                        <span class="caret"></span>
                        <span class="sr-only">info</span>
                    </button>
                    <ul dropdownMenu class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a>
                        </li>
                        <li><a href="#">Another action</a>
                        </li>
                        <li><a href="#">Something else here</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a>
                        </li>
                    </ul>
                </div>
                <!-- END button group-->
                <!-- START button group-->
                <div class="btn-group" dropdown>
                    <button class="btn btn-warning" type="button">Action</button>
                    <button class="btn dropdown-toggle btn-warning" type="button" dropdownToggle>
                        <span class="caret"></span>
                        <span class="sr-only">warning</span>
                    </button>
                    <ul dropdownMenu class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a>
                        </li>
                        <li><a href="#">Another action</a>
                        </li>
                        <li><a href="#">Something else here</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a>
                        </li>
                    </ul>
                </div>
                <!-- END button group-->
                <!-- START button group-->
                <div class="btn-group" dropdown>
                    <button class="btn btn-danger" type="button">Action</button>
                    <button class="btn dropdown-toggle btn-danger" type="button" dropdownToggle>
                        <span class="caret"></span>
                        <span class="sr-only">danger</span>
                    </button>
                    <ul dropdownMenu class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a>
                        </li>
                        <li><a href="#">Another action</a>
                        </li>
                        <li><a href="#">Something else here</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a>
                        </li>
                    </ul>
                </div>
                <!-- END button group-->
                <!-- START button group-->
                <div class="btn-group" dropdown>
                    <button class="btn btn-inverse" type="button">Action</button>
                    <button class="btn dropdown-toggle btn-inverse" type="button" dropdownToggle>
                        <span class="caret"></span>
                        <span class="sr-only">inverse</span>
                    </button>
                    <ul dropdownMenu class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a>
                        </li>
                        <li><a href="#">Another action</a>
                        </li>
                        <li><a href="#">Something else here</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a>
                        </li>
                    </ul>
                </div>
                <!-- END button group-->
            </div>
        </div>
        <!-- END panel-->
    </div>
</div>
<!-- END row-->
<!-- START panel-->
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Button actions</h3>
    </div>
    <div class="panel-body">
        <!-- START row-->
        <div class="row">
            <div class="col-lg-4">
                <h4>Single toggle</h4><pre>{{singleModel}}</pre>
                <button class="btn btn-primary" type="button" [(ngModel)]="singleModel" btnCheckbox>Single Toggle</button>
            </div>
            <div class="col-lg-4">
                <h4>Checkbox</h4>
                <pre>{{checkModel | json}}</pre>
                <div class="btn-group">
                    <label class="btn btn-primary" [(ngModel)]="checkModel.left" btnCheckbox>Left</label>
                    <label class="btn btn-primary" [(ngModel)]="checkModel.middle" btnCheckbox>Middle</label>
                    <label class="btn btn-primary" [(ngModel)]="checkModel.right" btnCheckbox>Right</label>
                </div>
            </div>
            <div class="col-lg-4">
                <h4>Radio &amp; Uncheckable Radio</h4><pre>{{radioModel || 'null'}}</pre>
                <div class="btn-group">
                    <label class="btn btn-primary" [(ngModel)]="radioModel" btnRadio="'Left'">Left</label>
                    <label class="btn btn-primary" [(ngModel)]="radioModel" btnRadio="'Middle'">Middle</label>
                    <label class="btn btn-primary" [(ngModel)]="radioModel" btnRadio="'Right'">Right</label>
                </div>
                <div class="btn-group">
                    <label class="btn btn-success" [(ngModel)]="radioModel" btnRadio="'Left'" uncheckable >Left</label>
                    <label class="btn btn-success" [(ngModel)]="radioModel" btnRadio="'Middle'" uncheckable >Middle</label>
                    <label class="btn btn-success" [(ngModel)]="radioModel" btnRadio="'Right'" uncheckable >Right</label>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- START panel-->
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Pagination</h3>
    </div>
    <div class="panel-body">
        <!-- START row-->
        <div class="row">
            <div class="col-lg-6">
                <div>
                    <h4>Default</h4>
                    <pagination [totalItems]="totalItems" [(ngModel)]="currentPage" (pageChanged)="pageChanged($event)"></pagination>
                    <pagination [directionLinks]="false" [totalItems]="totalItems" [(ngModel)]="currentPage" (numPages)="smallnumPages"></pagination>
                    <pre>The selected page no: {{currentPage}}</pre>
                    <button class="btn btn-info" (click)="setPage(3)">Set current page to: 3</button>
                </div>
            </div>
            <div class="col-lg-6">
                <h4>Pager</h4>
                <pager [totalItems]="totalItems" [(ngModel)]="currentPage"></pager>
                <hr/>
                <h4>Limit the maximum visible buttons</h4>
                <pagination class="pagination-sm" [totalItems]="bigTotalItems" [(ngModel)]="bigCurrentPage" [maxSize]="maxSize" [boundaryLinks]="true"></pagination>
                <pagination class="pagination-sm" [totalItems]="bigTotalItems" [(ngModel)]="bigCurrentPage" [maxSize]="maxSize" [boundaryLinks]="true" [rotate]="false" (numPages)="numPages"></pagination>
                <pre>Page: {{bigCurrentPage}} / {{numPages}}</pre>
            </div>
        </div>
        <!-- END row-->
    </div>
</div>
<!-- END panel-->
